-- ============================================================
-- COUNTRY existe como domain_catalogs desde 008_seeds.sql pero nunca
-- tuvo ningún catalog_value sembrado (mismo caso que gap #11) — un
-- sistema global no puede registrar la nacionalidad de un viajero, el
-- país de residencia, ni el país de un centro médico/profesional sin
-- esto. Lista de referencia (código ISO 3166-1 alpha-2 + nombre es/en),
-- a validar por el equipo de producto si necesitan la lista completa
-- oficial de 195+ países/territorios para uso legal/compliance — esta
-- cubre los mercados donde el sistema opera hoy más los principales
-- destinos de turismo médico/viaje.
-- ============================================================

INSERT INTO params.catalog_values (domain_id, code, label_es, label_en, display_order, is_system, lifecycle_status)
SELECT dc.id, v.code, v.es, v.en, v.ord, TRUE, 'ACTIVE'
FROM params.domain_catalogs dc
JOIN (VALUES
  ('AR', 'Argentina', 'Argentina', 1),
  ('BO', 'Bolivia', 'Bolivia', 2),
  ('BR', 'Brasil', 'Brazil', 3),
  ('CL', 'Chile', 'Chile', 4),
  ('CO', 'Colombia', 'Colombia', 5),
  ('CR', 'Costa Rica', 'Costa Rica', 6),
  ('CU', 'Cuba', 'Cuba', 7),
  ('DO', 'República Dominicana', 'Dominican Republic', 8),
  ('EC', 'Ecuador', 'Ecuador', 9),
  ('SV', 'El Salvador', 'El Salvador', 10),
  ('GT', 'Guatemala', 'Guatemala', 11),
  ('HN', 'Honduras', 'Honduras', 12),
  ('MX', 'México', 'Mexico', 13),
  ('NI', 'Nicaragua', 'Nicaragua', 14),
  ('PA', 'Panamá', 'Panama', 15),
  ('PY', 'Paraguay', 'Paraguay', 16),
  ('PE', 'Perú', 'Peru', 17),
  ('PR', 'Puerto Rico', 'Puerto Rico', 18),
  ('UY', 'Uruguay', 'Uruguay', 19),
  ('VE', 'Venezuela', 'Venezuela', 20),
  ('US', 'Estados Unidos', 'United States', 21),
  ('CA', 'Canadá', 'Canada', 22),
  ('ES', 'España', 'Spain', 23),
  ('PT', 'Portugal', 'Portugal', 24),
  ('FR', 'Francia', 'France', 25),
  ('DE', 'Alemania', 'Germany', 26),
  ('IT', 'Italia', 'Italy', 27),
  ('GB', 'Reino Unido', 'United Kingdom', 28),
  ('IE', 'Irlanda', 'Ireland', 29),
  ('NL', 'Países Bajos', 'Netherlands', 30),
  ('BE', 'Bélgica', 'Belgium', 31),
  ('CH', 'Suiza', 'Switzerland', 32),
  ('AT', 'Austria', 'Austria', 33),
  ('SE', 'Suecia', 'Sweden', 34),
  ('NO', 'Noruega', 'Norway', 35),
  ('DK', 'Dinamarca', 'Denmark', 36),
  ('FI', 'Finlandia', 'Finland', 37),
  ('PL', 'Polonia', 'Poland', 38),
  ('GR', 'Grecia', 'Greece', 39),
  ('TR', 'Turquía', 'Turkey', 40),
  ('RU', 'Rusia', 'Russia', 41),
  ('UA', 'Ucrania', 'Ukraine', 42),
  ('RO', 'Rumania', 'Romania', 43),
  ('HU', 'Hungría', 'Hungary', 44),
  ('CZ', 'República Checa', 'Czech Republic', 45),
  ('SK', 'Eslovaquia', 'Slovakia', 46),
  ('HR', 'Croacia', 'Croatia', 47),
  ('RS', 'Serbia', 'Serbia', 48),
  ('BG', 'Bulgaria', 'Bulgaria', 49),
  ('IS', 'Islandia', 'Iceland', 50),
  ('LU', 'Luxemburgo', 'Luxembourg', 51),
  ('MT', 'Malta', 'Malta', 52),
  ('CY', 'Chipre', 'Cyprus', 53),
  ('AD', 'Andorra', 'Andorra', 54),
  ('MC', 'Mónaco', 'Monaco', 55),
  ('CN', 'China', 'China', 56),
  ('JP', 'Japón', 'Japan', 57),
  ('KR', 'Corea del Sur', 'South Korea', 58),
  ('IN', 'India', 'India', 59),
  ('ID', 'Indonesia', 'Indonesia', 60),
  ('TH', 'Tailandia', 'Thailand', 61),
  ('VN', 'Vietnam', 'Vietnam', 62),
  ('PH', 'Filipinas', 'Philippines', 63),
  ('MY', 'Malasia', 'Malaysia', 64),
  ('SG', 'Singapur', 'Singapore', 65),
  ('TW', 'Taiwán', 'Taiwan', 66),
  ('HK', 'Hong Kong', 'Hong Kong', 67),
  ('PK', 'Pakistán', 'Pakistan', 68),
  ('BD', 'Bangladés', 'Bangladesh', 69),
  ('NP', 'Nepal', 'Nepal', 70),
  ('LK', 'Sri Lanka', 'Sri Lanka', 71),
  ('KZ', 'Kazajistán', 'Kazakhstan', 72),
  ('UZ', 'Uzbekistán', 'Uzbekistan', 73),
  ('AE', 'Emiratos Árabes Unidos', 'United Arab Emirates', 74),
  ('SA', 'Arabia Saudita', 'Saudi Arabia', 75),
  ('QA', 'Catar', 'Qatar', 76),
  ('KW', 'Kuwait', 'Kuwait', 77),
  ('BH', 'Baréin', 'Bahrain', 78),
  ('OM', 'Omán', 'Oman', 79),
  ('IL', 'Israel', 'Israel', 80),
  ('JO', 'Jordania', 'Jordan', 81),
  ('LB', 'Líbano', 'Lebanon', 82),
  ('IQ', 'Irak', 'Iraq', 83),
  ('IR', 'Irán', 'Iran', 84),
  ('AF', 'Afganistán', 'Afghanistan', 85),
  ('EG', 'Egipto', 'Egypt', 86),
  ('MA', 'Marruecos', 'Morocco', 87),
  ('DZ', 'Argelia', 'Algeria', 88),
  ('TN', 'Túnez', 'Tunisia', 89),
  ('LY', 'Libia', 'Libya', 90),
  ('ZA', 'Sudáfrica', 'South Africa', 91),
  ('NG', 'Nigeria', 'Nigeria', 92),
  ('KE', 'Kenia', 'Kenya', 93),
  ('ET', 'Etiopía', 'Ethiopia', 94),
  ('GH', 'Ghana', 'Ghana', 95),
  ('TZ', 'Tanzania', 'Tanzania', 96),
  ('UG', 'Uganda', 'Uganda', 97),
  ('SN', 'Senegal', 'Senegal', 98),
  ('CI', 'Costa de Marfil', 'Ivory Coast', 99),
  ('CM', 'Camerún', 'Cameroon', 100),
  ('AO', 'Angola', 'Angola', 101),
  ('MZ', 'Mozambique', 'Mozambique', 102),
  ('ZW', 'Zimbabue', 'Zimbabwe', 103),
  ('NA', 'Namibia', 'Namibia', 104),
  ('BW', 'Botsuana', 'Botswana', 105),
  ('ZM', 'Zambia', 'Zambia', 106),
  ('AU', 'Australia', 'Australia', 107),
  ('NZ', 'Nueva Zelanda', 'New Zealand', 108),
  ('FJ', 'Fiyi', 'Fiji', 109),
  ('PG', 'Papúa Nueva Guinea', 'Papua New Guinea', 110),
  ('GE', 'Georgia', 'Georgia', 111),
  ('AM', 'Armenia', 'Armenia', 112),
  ('AZ', 'Azerbaiyán', 'Azerbaijan', 113),
  ('BY', 'Bielorrusia', 'Belarus', 114),
  ('MD', 'Moldavia', 'Moldova', 115),
  ('LT', 'Lituania', 'Lithuania', 116),
  ('LV', 'Letonia', 'Latvia', 117),
  ('EE', 'Estonia', 'Estonia', 118),
  ('SI', 'Eslovenia', 'Slovenia', 119),
  ('BA', 'Bosnia y Herzegovina', 'Bosnia and Herzegovina', 120),
  ('MK', 'Macedonia del Norte', 'North Macedonia', 121),
  ('AL', 'Albania', 'Albania', 122),
  ('ME', 'Montenegro', 'Montenegro', 123),
  ('XK', 'Kosovo', 'Kosovo', 124),
  ('MN', 'Mongolia', 'Mongolia', 125),
  ('KH', 'Camboya', 'Cambodia', 126),
  ('LA', 'Laos', 'Laos', 127),
  ('MM', 'Myanmar', 'Myanmar', 128),
  ('BT', 'Bután', 'Bhutan', 129),
  ('MV', 'Maldivas', 'Maldives', 130),
  ('BN', 'Brunéi', 'Brunei', 131),
  ('TL', 'Timor Oriental', 'East Timor', 132),
  ('YE', 'Yemen', 'Yemen', 133),
  ('SY', 'Siria', 'Syria', 134),
  ('SD', 'Sudán', 'Sudan', 135),
  ('SS', 'Sudán del Sur', 'South Sudan', 136),
  ('RW', 'Ruanda', 'Rwanda', 137),
  ('BI', 'Burundi', 'Burundi', 138),
  ('MW', 'Malaui', 'Malawi', 139),
  ('MG', 'Madagascar', 'Madagascar', 140),
  ('MU', 'Mauricio', 'Mauritius', 141),
  ('SC', 'Seychelles', 'Seychelles', 142),
  ('BJ', 'Benín', 'Benin', 143),
  ('TG', 'Togo', 'Togo', 144),
  ('BF', 'Burkina Faso', 'Burkina Faso', 145),
  ('ML', 'Malí', 'Mali', 146),
  ('NE', 'Níger', 'Niger', 147),
  ('TD', 'Chad', 'Chad', 148),
  ('GA', 'Gabón', 'Gabon', 149),
  ('CG', 'Congo', 'Congo', 150),
  ('CD', 'República Democrática del Congo', 'DR Congo', 151),
  ('GQ', 'Guinea Ecuatorial', 'Equatorial Guinea', 152),
  ('DJ', 'Yibuti', 'Djibouti', 153),
  ('SO', 'Somalia', 'Somalia', 154),
  ('ER', 'Eritrea', 'Eritrea', 155),
  ('LS', 'Lesoto', 'Lesotho', 156),
  ('SZ', 'Esuatini', 'Eswatini', 157),
  ('GY', 'Guyana', 'Guyana', 158),
  ('SR', 'Surinam', 'Suriname', 159),
  ('BZ', 'Belice', 'Belize', 160),
  ('JM', 'Jamaica', 'Jamaica', 161),
  ('HT', 'Haití', 'Haiti', 162),
  ('TT', 'Trinidad y Tobago', 'Trinidad and Tobago', 163),
  ('BS', 'Bahamas', 'Bahamas', 164),
  ('BB', 'Barbados', 'Barbados', 165)
) AS v(code, es, en, ord) ON dc.code = 'COUNTRY'
WHERE NOT EXISTS (
  SELECT 1 FROM params.catalog_values cv
  WHERE cv.domain_id = dc.id AND cv.code = v.code
);
